// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"Orb/pkg/types"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
)

// CreateSubscriptionApplicationJSONExternalMarketplace - Optionally provide the name of the external marketplace that the subscription is attached to.
type CreateSubscriptionApplicationJSONExternalMarketplace string

const (
	CreateSubscriptionApplicationJSONExternalMarketplaceGoogle CreateSubscriptionApplicationJSONExternalMarketplace = "google"
	CreateSubscriptionApplicationJSONExternalMarketplaceAws    CreateSubscriptionApplicationJSONExternalMarketplace = "aws"
	CreateSubscriptionApplicationJSONExternalMarketplaceAzure  CreateSubscriptionApplicationJSONExternalMarketplace = "azure"
)

func (e CreateSubscriptionApplicationJSONExternalMarketplace) ToPointer() *CreateSubscriptionApplicationJSONExternalMarketplace {
	return &e
}

func (e *CreateSubscriptionApplicationJSONExternalMarketplace) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "google":
		fallthrough
	case "aws":
		fallthrough
	case "azure":
		*e = CreateSubscriptionApplicationJSONExternalMarketplace(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONExternalMarketplace: %v", v)
	}
}

type CreateSubscriptionApplicationJSONPhaseOverrides struct {
	Discount *shared.Discount `json:"discount,omitempty"`
	// The new minimum amount for the phase. Providing `null` will clear the existing minimum, if it exists.
	MinimumAmount *string `json:"minimum_amount,omitempty"`
	// The phase order that is being modified.
	Order *float64 `json:"order,omitempty"`
}

type CreateSubscriptionApplicationJSONPriceOverrides7ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides7ModelTypeTieredBps CreateSubscriptionApplicationJSONPriceOverrides7ModelType = "tiered_bps"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides7ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides7ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides7ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tiered_bps":
		*e = CreateSubscriptionApplicationJSONPriceOverrides7ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides7ModelType: %v", v)
	}
}

type CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfigTiers struct {
	Bps            float64 `json:"bps"`
	MaximumAmount  string  `json:"maximum_amount"`
	MinimumAmount  string  `json:"minimum_amount"`
	PerUnitMaximum string  `json:"per_unit_maximum"`
}

type CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfig struct {
	Tiers []CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfigTiers `json:"tiers"`
}

// CreateSubscriptionApplicationJSONPriceOverrides7 - Tiered BPS price override
type CreateSubscriptionApplicationJSONPriceOverrides7 struct {
	// The subscription's override discount for this price.
	Discount *shared.CreateDiscount `json:"discount,omitempty"`
	ID       string                 `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount   *string                                                         `json:"minimum_amount,omitempty"`
	ModelType       CreateSubscriptionApplicationJSONPriceOverrides7ModelType       `json:"model_type"`
	TieredBpsConfig CreateSubscriptionApplicationJSONPriceOverrides7TieredBpsConfig `json:"tiered_bps_config"`
}

type CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfigTiers struct {
	Bps            float64 `json:"bps"`
	MaximumAmount  string  `json:"maximum_amount"`
	PerUnitMaximum string  `json:"per_unit_maximum"`
}

type CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfig struct {
	Tiers []CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfigTiers `json:"tiers,omitempty"`
}

type CreateSubscriptionApplicationJSONPriceOverrides6ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides6ModelTypeBulkBps CreateSubscriptionApplicationJSONPriceOverrides6ModelType = "bulk_bps"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides6ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides6ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides6ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bulk_bps":
		*e = CreateSubscriptionApplicationJSONPriceOverrides6ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides6ModelType: %v", v)
	}
}

// CreateSubscriptionApplicationJSONPriceOverrides6 - Bulk BPS price override
type CreateSubscriptionApplicationJSONPriceOverrides6 struct {
	BulkBpsConfig *CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfig `json:"bulk_bps_config,omitempty"`
	// The subscription's override discount for this price.
	Discount *shared.CreateDiscount `json:"discount,omitempty"`
	ID       string                 `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                   `json:"minimum_amount,omitempty"`
	ModelType     CreateSubscriptionApplicationJSONPriceOverrides6ModelType `json:"model_type"`
}

type CreateSubscriptionApplicationJSONPriceOverrides5BpsConfig struct {
	Bps            float64 `json:"bps"`
	PerUnitMaximum string  `json:"per_unit_maximum"`
}

type CreateSubscriptionApplicationJSONPriceOverrides5ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides5ModelTypeBps CreateSubscriptionApplicationJSONPriceOverrides5ModelType = "bps"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides5ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides5ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides5ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bps":
		*e = CreateSubscriptionApplicationJSONPriceOverrides5ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides5ModelType: %v", v)
	}
}

// CreateSubscriptionApplicationJSONPriceOverrides5 - BPS price override
type CreateSubscriptionApplicationJSONPriceOverrides5 struct {
	BpsConfig CreateSubscriptionApplicationJSONPriceOverrides5BpsConfig `json:"bps_config"`
	// The subscription's override discount for this price.
	Discount *shared.CreateDiscount `json:"discount,omitempty"`
	ID       string                 `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                   `json:"minimum_amount,omitempty"`
	ModelType     CreateSubscriptionApplicationJSONPriceOverrides5ModelType `json:"model_type"`
}

type CreateSubscriptionApplicationJSONPriceOverrides4ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides4ModelTypePackage CreateSubscriptionApplicationJSONPriceOverrides4ModelType = "package"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides4ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides4ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides4ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "package":
		*e = CreateSubscriptionApplicationJSONPriceOverrides4ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides4ModelType: %v", v)
	}
}

type CreateSubscriptionApplicationJSONPriceOverrides4PackageConfig struct {
	PackageAmount string  `json:"package_amount"`
	PackageSize   float64 `json:"package_size"`
}

// CreateSubscriptionApplicationJSONPriceOverrides4 - Package price override
type CreateSubscriptionApplicationJSONPriceOverrides4 struct {
	// The subscription's override discount for this price.
	Discount *shared.CreateDiscount `json:"discount,omitempty"`
	ID       string                 `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                       `json:"minimum_amount,omitempty"`
	ModelType     CreateSubscriptionApplicationJSONPriceOverrides4ModelType     `json:"model_type"`
	PackageConfig CreateSubscriptionApplicationJSONPriceOverrides4PackageConfig `json:"package_config"`
}

type CreateSubscriptionApplicationJSONPriceOverrides3BulkConfigTiers struct {
	MaximumUnits string `json:"maximum_units"`
	UnitAmount   string `json:"unit_amount"`
}

type CreateSubscriptionApplicationJSONPriceOverrides3BulkConfig struct {
	Tiers []CreateSubscriptionApplicationJSONPriceOverrides3BulkConfigTiers `json:"tiers"`
}

type CreateSubscriptionApplicationJSONPriceOverrides3ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides3ModelTypeBulk CreateSubscriptionApplicationJSONPriceOverrides3ModelType = "bulk"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides3ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides3ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides3ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bulk":
		*e = CreateSubscriptionApplicationJSONPriceOverrides3ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides3ModelType: %v", v)
	}
}

// CreateSubscriptionApplicationJSONPriceOverrides3 - Bulk price override
type CreateSubscriptionApplicationJSONPriceOverrides3 struct {
	BulkConfig CreateSubscriptionApplicationJSONPriceOverrides3BulkConfig `json:"bulk_config"`
	// The subscription's override discount for this price.
	Discount *shared.CreateDiscount `json:"discount,omitempty"`
	ID       string                 `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                   `json:"minimum_amount,omitempty"`
	ModelType     CreateSubscriptionApplicationJSONPriceOverrides3ModelType `json:"model_type"`
}

type CreateSubscriptionApplicationJSONPriceOverrides2ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides2ModelTypeUnit CreateSubscriptionApplicationJSONPriceOverrides2ModelType = "unit"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides2ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides2ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides2ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unit":
		*e = CreateSubscriptionApplicationJSONPriceOverrides2ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides2ModelType: %v", v)
	}
}

type CreateSubscriptionApplicationJSONPriceOverrides2UnitConfig struct {
	UnitAmount string `json:"unit_amount"`
}

// CreateSubscriptionApplicationJSONPriceOverrides2 - Unit price override
type CreateSubscriptionApplicationJSONPriceOverrides2 struct {
	// The subscription's override discount for this price.
	Discount           *shared.CreateDiscount `json:"discount,omitempty"`
	FixedPriceQuantity *int64                 `json:"fixed_price_quantity,omitempty"`
	ID                 string                 `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                    `json:"minimum_amount,omitempty"`
	ModelType     CreateSubscriptionApplicationJSONPriceOverrides2ModelType  `json:"model_type"`
	UnitConfig    CreateSubscriptionApplicationJSONPriceOverrides2UnitConfig `json:"unit_config"`
}

type CreateSubscriptionApplicationJSONPriceOverrides1ModelType string

const (
	CreateSubscriptionApplicationJSONPriceOverrides1ModelTypeTiered CreateSubscriptionApplicationJSONPriceOverrides1ModelType = "tiered"
)

func (e CreateSubscriptionApplicationJSONPriceOverrides1ModelType) ToPointer() *CreateSubscriptionApplicationJSONPriceOverrides1ModelType {
	return &e
}

func (e *CreateSubscriptionApplicationJSONPriceOverrides1ModelType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tiered":
		*e = CreateSubscriptionApplicationJSONPriceOverrides1ModelType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateSubscriptionApplicationJSONPriceOverrides1ModelType: %v", v)
	}
}

type CreateSubscriptionApplicationJSONPriceOverrides1TieredConfigTiers struct {
	FirstUnit  *string `json:"first_unit,omitempty"`
	LastUnit   *string `json:"last_unit,omitempty"`
	UnitAmount *string `json:"unit_amount,omitempty"`
}

type CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig struct {
	Tiers []CreateSubscriptionApplicationJSONPriceOverrides1TieredConfigTiers `json:"tiers,omitempty"`
}

// CreateSubscriptionApplicationJSONPriceOverrides1 - Tiered price override
type CreateSubscriptionApplicationJSONPriceOverrides1 struct {
	// The subscription's override discount for this price.
	Discount *shared.CreateDiscount `json:"discount,omitempty"`
	// price_id
	ID string `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                      `json:"minimum_amount,omitempty"`
	ModelType     CreateSubscriptionApplicationJSONPriceOverrides1ModelType    `json:"model_type"`
	TieredConfig  CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig `json:"tiered_config"`
}

type CreateSubscriptionApplicationJSONPriceOverridesType string

const (
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides1 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_1"
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides2 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_2"
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides3 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_3"
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides4 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_4"
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides5 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_5"
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides6 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_6"
	CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides7 CreateSubscriptionApplicationJSONPriceOverridesType = "create-subscription_ApplicationJSON_price_overrides_7"
)

type CreateSubscriptionApplicationJSONPriceOverrides struct {
	CreateSubscriptionApplicationJSONPriceOverrides1 *CreateSubscriptionApplicationJSONPriceOverrides1
	CreateSubscriptionApplicationJSONPriceOverrides2 *CreateSubscriptionApplicationJSONPriceOverrides2
	CreateSubscriptionApplicationJSONPriceOverrides3 *CreateSubscriptionApplicationJSONPriceOverrides3
	CreateSubscriptionApplicationJSONPriceOverrides4 *CreateSubscriptionApplicationJSONPriceOverrides4
	CreateSubscriptionApplicationJSONPriceOverrides5 *CreateSubscriptionApplicationJSONPriceOverrides5
	CreateSubscriptionApplicationJSONPriceOverrides6 *CreateSubscriptionApplicationJSONPriceOverrides6
	CreateSubscriptionApplicationJSONPriceOverrides7 *CreateSubscriptionApplicationJSONPriceOverrides7

	Type CreateSubscriptionApplicationJSONPriceOverridesType
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides1(createSubscriptionApplicationJSONPriceOverrides1 CreateSubscriptionApplicationJSONPriceOverrides1) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides1

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides1: &createSubscriptionApplicationJSONPriceOverrides1,
		Type: typ,
	}
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides2(createSubscriptionApplicationJSONPriceOverrides2 CreateSubscriptionApplicationJSONPriceOverrides2) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides2

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides2: &createSubscriptionApplicationJSONPriceOverrides2,
		Type: typ,
	}
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides3(createSubscriptionApplicationJSONPriceOverrides3 CreateSubscriptionApplicationJSONPriceOverrides3) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides3

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides3: &createSubscriptionApplicationJSONPriceOverrides3,
		Type: typ,
	}
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides4(createSubscriptionApplicationJSONPriceOverrides4 CreateSubscriptionApplicationJSONPriceOverrides4) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides4

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides4: &createSubscriptionApplicationJSONPriceOverrides4,
		Type: typ,
	}
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides5(createSubscriptionApplicationJSONPriceOverrides5 CreateSubscriptionApplicationJSONPriceOverrides5) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides5

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides5: &createSubscriptionApplicationJSONPriceOverrides5,
		Type: typ,
	}
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides6(createSubscriptionApplicationJSONPriceOverrides6 CreateSubscriptionApplicationJSONPriceOverrides6) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides6

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides6: &createSubscriptionApplicationJSONPriceOverrides6,
		Type: typ,
	}
}

func CreateCreateSubscriptionApplicationJSONPriceOverridesCreateSubscriptionApplicationJSONPriceOverrides7(createSubscriptionApplicationJSONPriceOverrides7 CreateSubscriptionApplicationJSONPriceOverrides7) CreateSubscriptionApplicationJSONPriceOverrides {
	typ := CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides7

	return CreateSubscriptionApplicationJSONPriceOverrides{
		CreateSubscriptionApplicationJSONPriceOverrides7: &createSubscriptionApplicationJSONPriceOverrides7,
		Type: typ,
	}
}

func (u *CreateSubscriptionApplicationJSONPriceOverrides) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	createSubscriptionApplicationJSONPriceOverrides1 := new(CreateSubscriptionApplicationJSONPriceOverrides1)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides1); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides1 = createSubscriptionApplicationJSONPriceOverrides1
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides1
		return nil
	}

	createSubscriptionApplicationJSONPriceOverrides2 := new(CreateSubscriptionApplicationJSONPriceOverrides2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides2); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides2 = createSubscriptionApplicationJSONPriceOverrides2
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides2
		return nil
	}

	createSubscriptionApplicationJSONPriceOverrides3 := new(CreateSubscriptionApplicationJSONPriceOverrides3)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides3); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides3 = createSubscriptionApplicationJSONPriceOverrides3
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides3
		return nil
	}

	createSubscriptionApplicationJSONPriceOverrides4 := new(CreateSubscriptionApplicationJSONPriceOverrides4)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides4); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides4 = createSubscriptionApplicationJSONPriceOverrides4
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides4
		return nil
	}

	createSubscriptionApplicationJSONPriceOverrides5 := new(CreateSubscriptionApplicationJSONPriceOverrides5)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides5); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides5 = createSubscriptionApplicationJSONPriceOverrides5
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides5
		return nil
	}

	createSubscriptionApplicationJSONPriceOverrides6 := new(CreateSubscriptionApplicationJSONPriceOverrides6)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides6); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides6 = createSubscriptionApplicationJSONPriceOverrides6
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides6
		return nil
	}

	createSubscriptionApplicationJSONPriceOverrides7 := new(CreateSubscriptionApplicationJSONPriceOverrides7)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createSubscriptionApplicationJSONPriceOverrides7); err == nil {
		u.CreateSubscriptionApplicationJSONPriceOverrides7 = createSubscriptionApplicationJSONPriceOverrides7
		u.Type = CreateSubscriptionApplicationJSONPriceOverridesTypeCreateSubscriptionApplicationJSONPriceOverrides7
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CreateSubscriptionApplicationJSONPriceOverrides) MarshalJSON() ([]byte, error) {
	if u.CreateSubscriptionApplicationJSONPriceOverrides1 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides1)
	}

	if u.CreateSubscriptionApplicationJSONPriceOverrides2 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides2)
	}

	if u.CreateSubscriptionApplicationJSONPriceOverrides3 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides3)
	}

	if u.CreateSubscriptionApplicationJSONPriceOverrides4 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides4)
	}

	if u.CreateSubscriptionApplicationJSONPriceOverrides5 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides5)
	}

	if u.CreateSubscriptionApplicationJSONPriceOverrides6 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides6)
	}

	if u.CreateSubscriptionApplicationJSONPriceOverrides7 != nil {
		return json.Marshal(u.CreateSubscriptionApplicationJSONPriceOverrides7)
	}

	return nil, nil
}

type CreateSubscriptionApplicationJSON struct {
	// Align billing periods with the subscription's start_date. If this is not provided, this defaults to aligning billing periods with the start of the month.
	AlignBillingWithSubscriptionStartDate *bool `json:"align_billing_with_subscription_start_date,omitempty"`
	// Used to determine whether Orb will attempt to automatically charge the payment method on file for the customer corresponding to this subscription. If not provided, the property on the corresponding customer will be honored.
	AutoCollection *bool `json:"auto_collection,omitempty"`
	// Redemption code to be used for this subscription. If the coupon cannot be found by its redemption code, or cannot be redeemed, an error response will be returned and the plan change will not be scheduled.
	CouponRedemptionCode *string `json:"coupon_redemption_code,omitempty"`
	// The ID of the customer to subscribe.
	CustomerID *string `json:"customer_id,omitempty"`
	// Invoices for this subscription will populate with this memo. When not set, the plan-level setting for memo will be used.
	DefaultInvoiceMemo *string `json:"default_invoice_memo,omitempty"`
	// The external ID of the customer to subscribe, as an alternate to passing the `customer_id`.
	ExternalCustomerID *string `json:"external_customer_id,omitempty"`
	// Optionally provide the name of the external marketplace that the subscription is attached to.
	ExternalMarketplace *CreateSubscriptionApplicationJSONExternalMarketplace `json:"external_marketplace,omitempty"`
	// The reporting ID to associate this subscription with the external marketplace. Required if external_marketplace is specified.
	ExternalMarketplaceReportingID *string `json:"external_marketplace_reporting_id,omitempty"`
	// The external ID of the plan, which can be used in place of the `plan_id`.
	ExternalPlanID *string `json:"external_plan_id,omitempty"`
	// User-specified key value pairs, often useful for referencing internal resources or IDs. Returned as-is in the subscription resource.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// The subscription's override minimum amount for the plan.
	MinimumAmount *string `json:"minimum_amount,omitempty"`
	// The net terms of a subscription determine when a subscription's invoice is due relative to its issue date. Whereas a net terms of 0 signifies "due on issue", a net terms of 30 can be used to provide the customer one month to pay the invoice. By default, the subscription defaults to the plan's net terms configuration.
	NetTerms *int64 `json:"net_terms,omitempty"`
	// Optionally provide a list of minimum amount or discount overrides for phases on the plan.
	PhaseOverrides []CreateSubscriptionApplicationJSONPhaseOverrides `json:"phase_overrides,omitempty"`
	// The plan that the given customer should be subscribed to. The plan determines the pricing and cadence of the subscription.
	PlanID *string `json:"plan_id,omitempty"`
	// Optionally provide a list of overrides for prices on the plan
	PriceOverrides []CreateSubscriptionApplicationJSONPriceOverrides `json:"price_overrides,omitempty"`
	// The date that Orb should start billing for the subscription, localized to the customer's timezone. If this is not provided, this defaults to the current date in the customer's timezone.
	StartDate *types.Date `json:"start_date,omitempty"`
}

type CreateSubscriptionJSONResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Subscription *shared.Subscription
}
