// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteCustomerRequest struct {
	// Orb customer ID
	CustomerID string `pathParam:"style=simple,explode=false,name=customer_id"`
}

type DeleteCustomerResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
