// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeprecateEventRequest struct {
	// Identical to the `idempotency_key` provided on event ingestion. Uniquely identifies an event in the system.
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

// DeprecateEvent400ApplicationJSON - Bad Request
type DeprecateEvent400ApplicationJSON struct {
	// HTTP Code
	Status *int64 `json:"status,omitempty"`
	// Error message
	Title *string `json:"title,omitempty"`
	Type  *string `json:"type,omitempty"`
	// An array of strings corresponding to the validation failures
	ValidationErrors []string `json:"validation_errors,omitempty"`
}

// DeprecateEvent200ApplicationJSON - OK
type DeprecateEvent200ApplicationJSON struct {
	// event_id of the deprecated event, if successfully updated
	Deprecated *string `json:"deprecated,omitempty"`
}

type DeprecateEventResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	DeprecateEvent200ApplicationJSONObject *DeprecateEvent200ApplicationJSON
	// Bad Request
	DeprecateEvent400ApplicationJSONObject *DeprecateEvent400ApplicationJSON
}
