// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
	"time"
)

type FetchSubscriptionScheduleRequest struct {
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscription_id"`
}

type FetchSubscriptionSchedule200ApplicationJSONDataPlan struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type FetchSubscriptionSchedule200ApplicationJSONData struct {
	EndDate   *time.Time                                           `json:"end_date,omitempty"`
	Plan      *FetchSubscriptionSchedule200ApplicationJSONDataPlan `json:"plan,omitempty"`
	StartDate *time.Time                                           `json:"start_date,omitempty"`
}

// FetchSubscriptionSchedule200ApplicationJSON - OK
type FetchSubscriptionSchedule200ApplicationJSON struct {
	Data               []FetchSubscriptionSchedule200ApplicationJSONData `json:"data,omitempty"`
	PaginationMetadata *shared.PaginationMetadata                        `json:"pagination_metadata,omitempty"`
}

type FetchSubscriptionScheduleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	FetchSubscriptionSchedule200ApplicationJSONObject *FetchSubscriptionSchedule200ApplicationJSON
}
