// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"time"
)

type FetchCustomerCreditsRequest struct {
	// The Orb Customer ID
	CustomerID string `pathParam:"style=simple,explode=false,name=customer_id"`
}

type FetchCustomerCredits200ApplicationJSONData struct {
	// Remaining credits in this block
	Balance float64 `json:"balance"`
	// An ISO 8601 format date with a timezone offset that represents when this block of credits is no longer usable.
	ExpiryDate time.Time `json:"expiry_date"`
	ID         string    `json:"id"`
	// How much, in USD, a customer paid for a single credit in this block
	PerUnitCostBasis string `json:"per_unit_cost_basis"`
}

type FetchCustomerCredits200ApplicationJSONPaginationMetadata struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// FetchCustomerCredits200ApplicationJSON - OK
type FetchCustomerCredits200ApplicationJSON struct {
	Data               []FetchCustomerCredits200ApplicationJSONData             `json:"data"`
	PaginationMetadata FetchCustomerCredits200ApplicationJSONPaginationMetadata `json:"pagination_metadata"`
}

type FetchCustomerCreditsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	FetchCustomerCredits200ApplicationJSONObject *FetchCustomerCredits200ApplicationJSON
}
