// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type FetchCouponRequest struct {
	CouponID string `pathParam:"style=simple,explode=false,name=coupon_id"`
}

type FetchCouponResponse struct {
	ContentType string
	// OK
	Coupon      *shared.Coupon
	StatusCode  int
	RawResponse *http.Response
}
