// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

// FetchCustomerCreditsLedgerEntryStatus - Filters to a single status of ledger entry
type FetchCustomerCreditsLedgerEntryStatus string

const (
	FetchCustomerCreditsLedgerEntryStatusCommitted FetchCustomerCreditsLedgerEntryStatus = "committed"
	FetchCustomerCreditsLedgerEntryStatusPending   FetchCustomerCreditsLedgerEntryStatus = "pending"
)

func (e FetchCustomerCreditsLedgerEntryStatus) ToPointer() *FetchCustomerCreditsLedgerEntryStatus {
	return &e
}

func (e *FetchCustomerCreditsLedgerEntryStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "committed":
		fallthrough
	case "pending":
		*e = FetchCustomerCreditsLedgerEntryStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FetchCustomerCreditsLedgerEntryStatus: %v", v)
	}
}

// FetchCustomerCreditsLedgerEntryType - Filter to a single type of ledger entry
type FetchCustomerCreditsLedgerEntryType string

const (
	FetchCustomerCreditsLedgerEntryTypeIncrement         FetchCustomerCreditsLedgerEntryType = "increment"
	FetchCustomerCreditsLedgerEntryTypeDecrement         FetchCustomerCreditsLedgerEntryType = "decrement"
	FetchCustomerCreditsLedgerEntryTypeExpirationChange  FetchCustomerCreditsLedgerEntryType = "expiration_change"
	FetchCustomerCreditsLedgerEntryTypeCreditBlockExpiry FetchCustomerCreditsLedgerEntryType = "credit_block_expiry"
)

func (e FetchCustomerCreditsLedgerEntryType) ToPointer() *FetchCustomerCreditsLedgerEntryType {
	return &e
}

func (e *FetchCustomerCreditsLedgerEntryType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "increment":
		fallthrough
	case "decrement":
		fallthrough
	case "expiration_change":
		fallthrough
	case "credit_block_expiry":
		*e = FetchCustomerCreditsLedgerEntryType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FetchCustomerCreditsLedgerEntryType: %v", v)
	}
}

type FetchCustomerCreditsLedgerRequest struct {
	CustomerID string `pathParam:"style=simple,explode=false,name=customer_id"`
	// Filters to a single status of ledger entry
	EntryStatus *FetchCustomerCreditsLedgerEntryStatus `queryParam:"style=form,explode=true,name=entry_status"`
	// Filter to a single type of ledger entry
	EntryType *FetchCustomerCreditsLedgerEntryType `queryParam:"style=form,explode=true,name=entry_type"`
	// Filter to ledger entries that affect at least this amount
	MinimumAmount *float64 `queryParam:"style=form,explode=true,name=minimum_amount"`
}

type FetchCustomerCreditsLedger200ApplicationJSONPaginationMetadata struct {
	HasMore    bool   `json:"has_more"`
	NextCursor string `json:"next_cursor"`
}

// FetchCustomerCreditsLedger200ApplicationJSON - OK
type FetchCustomerCreditsLedger200ApplicationJSON struct {
	Data               []shared.CreditLedgerEntry                                     `json:"data"`
	PaginationMetadata FetchCustomerCreditsLedger200ApplicationJSONPaginationMetadata `json:"pagination_metadata"`
}

type FetchCustomerCreditsLedgerResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	FetchCustomerCreditsLedger200ApplicationJSONObject *FetchCustomerCreditsLedger200ApplicationJSON
}
