// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type FetchInvoiceRequest struct {
	InvoiceID string `pathParam:"style=simple,explode=false,name=invoice_id"`
}

type FetchInvoiceResponse struct {
	ContentType string
	// OK
	Invoice     *shared.Invoice
	StatusCode  int
	RawResponse *http.Response
}
