// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type GetCustomersCustomerIDBalanceTransactionsRequest struct {
	CustomerID string `pathParam:"style=simple,explode=false,name=customer_id"`
}

// GetCustomersCustomerIDBalanceTransactions200ApplicationJSON - OK
type GetCustomersCustomerIDBalanceTransactions200ApplicationJSON struct {
	Data               []shared.CustomerBalanceTransaction `json:"data,omitempty"`
	PaginationMetadata map[string]interface{}              `json:"pagination_metadata,omitempty"`
}

type GetCustomersCustomerIDBalanceTransactionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetCustomersCustomerIDBalanceTransactions200ApplicationJSONObject *GetCustomersCustomerIDBalanceTransactions200ApplicationJSON
}
