// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/orb-go/pkg/models/shared"
	"net/http"
)

type GetCustomersExternalCustomerIDExternalCustomerIDRequest struct {
	ExternalCustomerID string `pathParam:"style=simple,explode=false,name=external_customer_id"`
}

type GetCustomersExternalCustomerIDExternalCustomerIDResponse struct {
	ContentType string
	// OK
	Customer    *shared.Customer
	StatusCode  int
	RawResponse *http.Response
}
