// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/orb-go/pkg/models/shared"
	"net/http"
)

type GetInvoiceInvoiceIDRequest struct {
	InvoiceID string `pathParam:"style=simple,explode=false,name=invoice_id"`
}

type GetInvoiceInvoiceIDResponse struct {
	ContentType string
	// OK
	Invoice     *shared.Invoice
	StatusCode  int
	RawResponse *http.Response
}
