// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// GetPing200ApplicationJSON - OK
type GetPing200ApplicationJSON struct {
	Response string `json:"response"`
}

type GetPingResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetPing200ApplicationJSONObject *GetPing200ApplicationJSON
}
