// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/orb-go/pkg/models/shared"
	"net/http"
)

type GetPlansExternalPlanIDRequest struct {
	Plan           *shared.Plan `request:"mediaType=application/json"`
	ExternalPlanID string       `pathParam:"style=simple,explode=false,name=external_plan_id"`
}

type GetPlansExternalPlanIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
