// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/orb-go/pkg/models/shared"
	"net/http"
)

type GetPlansRequestBody struct {
	Data               []shared.Plan          `json:"data,omitempty"`
	PaginationMetadata map[string]interface{} `json:"pagination_metadata,omitempty"`
}

type GetPlansResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
