// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/orb-go/pkg/models/shared"
	"net/http"
)

type GetPlansPlanIDRequest struct {
	PlanID string `pathParam:"style=simple,explode=false,name=plan_id"`
}

type GetPlansPlanIDResponse struct {
	ContentType string
	// OK
	Plan        *shared.Plan
	StatusCode  int
	RawResponse *http.Response
}
