// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type ListCouponSubscriptionsRequest struct {
	CouponID string `pathParam:"style=simple,explode=false,name=coupon_id"`
}

// ListCouponSubscriptions200ApplicationJSON - OK
type ListCouponSubscriptions200ApplicationJSON struct {
	Data               []shared.Subscription      `json:"data,omitempty"`
	PaginationMetadata *shared.PaginationMetadata `json:"pagination_metadata,omitempty"`
}

type ListCouponSubscriptionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ListCouponSubscriptions200ApplicationJSONObject *ListCouponSubscriptions200ApplicationJSON
}
