// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

// ListBackfills200ApplicationJSON - OK
type ListBackfills200ApplicationJSON struct {
	Data               []shared.Backfill          `json:"data,omitempty"`
	PaginationMetadata *shared.PaginationMetadata `json:"pagination_metadata,omitempty"`
}

type ListBackfillsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ListBackfills200ApplicationJSONObject *ListBackfills200ApplicationJSON
}
