// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type ListBalanceTransactionsRequest struct {
	CustomerID string `pathParam:"style=simple,explode=false,name=customer_id"`
}

// ListBalanceTransactions200ApplicationJSON - OK
type ListBalanceTransactions200ApplicationJSON struct {
	Data               []shared.CustomerBalanceTransaction `json:"data,omitempty"`
	PaginationMetadata *shared.PaginationMetadata          `json:"pagination_metadata,omitempty"`
}

type ListBalanceTransactionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ListBalanceTransactions200ApplicationJSONObject *ListBalanceTransactions200ApplicationJSON
}
