// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

// ListPlans200ApplicationJSON - OK
type ListPlans200ApplicationJSON struct {
	Data               []shared.Plan              `json:"data,omitempty"`
	PaginationMetadata *shared.PaginationMetadata `json:"pagination_metadata,omitempty"`
}

type ListPlansResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ListPlans200ApplicationJSONObject *ListPlans200ApplicationJSON
}
