// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type ListCreditNoteRequest struct {
	// Filter by a specific customer (cannot be used with `external_customer_id`)
	CustomerID *string `queryParam:"style=form,explode=true,name=customer_id"`
	// Filter by a specific customer (cannot be used with `customer_id`)
	ExternalCustomerID *string `queryParam:"style=form,explode=true,name=external_customer_id"`
	// Filter by a specific subscription
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscription_id"`
}

// ListCreditNote200ApplicationJSON - OK
type ListCreditNote200ApplicationJSON struct {
	Data               []shared.CreditNote        `json:"data,omitempty"`
	PaginationMetadata *shared.PaginationMetadata `json:"pagination_metadata,omitempty"`
}

type ListCreditNoteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ListCreditNote200ApplicationJSONObject *ListCreditNote200ApplicationJSON
}
