// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type ListPlansRequestBody struct {
	Data               []shared.Plan          `json:"data,omitempty"`
	PaginationMetadata map[string]interface{} `json:"pagination_metadata,omitempty"`
}

type ListPlansResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
