// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"time"
)

type PatchCustomersCustomerIDUsageRequestBodyEvents struct {
	// A name to meaningfully identify the action or event type.
	EventName string `json:"event_name"`
	// A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
	Properties map[string]interface{} `json:"properties"`
	// An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent the time that usage was recorded, and is particularly important to attribute usage to a given billing period.
	Timestamp string `json:"timestamp"`
}

type PatchCustomersCustomerIDUsageRequestBody struct {
	Events []PatchCustomersCustomerIDUsageRequestBodyEvents `json:"events"`
}

type PatchCustomersCustomerIDUsageRequest struct {
	RequestBody *PatchCustomersCustomerIDUsageRequestBody `request:"mediaType=application/json"`
	CustomerID  string                                    `pathParam:"style=simple,explode=false,name=customer_id"`
	// This bound is exclusive (i.e. events before this timestamp will be updated)
	TimeframeEnd time.Time `queryParam:"style=form,explode=true,name=timeframe_end"`
	// This bound is inclusive (i.e. events with this timestamp onward, inclusive will be updated)
	TimeframeStart time.Time `queryParam:"style=form,explode=true,name=timeframe_start"`
}

type PatchCustomersCustomerIDUsage400ApplicationJSONValidationErrors struct {
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// An array of strings corresponding to each validation failure
	ValidationErrors []string `json:"validation_errors,omitempty"`
}

// PatchCustomersCustomerIDUsage400ApplicationJSON - Bad Request
type PatchCustomersCustomerIDUsage400ApplicationJSON struct {
	// HTTP Code
	Status int64 `json:"status"`
	// Error message
	Title string `json:"title"`
	Type  string `json:"type"`
	// Contains all failing validation events.
	ValidationErrors []PatchCustomersCustomerIDUsage400ApplicationJSONValidationErrors `json:"validation_errors"`
}

// PatchCustomersCustomerIDUsage200ApplicationJSON - OK
type PatchCustomersCustomerIDUsage200ApplicationJSON struct {
	// An array of strings, corresponding to idempotency_key's marked as duplicates (previously ingested)
	Duplicate []map[string]interface{} `json:"duplicate,omitempty"`
	// An array of strings, corresponding to idempotency_key's which were successfully ingested.
	Ingested []string `json:"ingested,omitempty"`
}

type PatchCustomersCustomerIDUsageResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PatchCustomersCustomerIDUsage200ApplicationJSONObject *PatchCustomersCustomerIDUsage200ApplicationJSON
	// Bad Request
	PatchCustomersCustomerIDUsage400ApplicationJSONObject *PatchCustomersCustomerIDUsage400ApplicationJSON
}
