// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// Ping200ApplicationJSON - OK
type Ping200ApplicationJSON struct {
	Response string `json:"response"`
}

type PingResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Ping200ApplicationJSONObject *Ping200ApplicationJSON
}
