// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type PostIngestRequestBodyEvents struct {
	// The Orb Customer identifier
	CustomerID *string `json:"customer_id,omitempty"`
	// A name to meaningfully identify the action or event type.
	EventName string `json:"event_name"`
	// An alias for the Orb customer, whose mapping is specified when creating the customer
	ExternalCustomerID *string `json:"external_customer_id,omitempty"`
	// A unique value, generated by the client, that is used to de-duplicate events. Exactly one event with a given idempotency key will be ingested, which allows for safe request retries.
	IdempotencyKey string `json:"idempotency_key"`
	// A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
	Properties map[string]interface{} `json:"properties"`
	// An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent the time that usage was recorded, and is particularly important to attribute usage to a given billing period.
	Timestamp string `json:"timestamp"`
}

type PostIngestRequestBody struct {
	Events []PostIngestRequestBodyEvents `json:"events"`
}

// PostIngestDebugEnum - Flag to enable additional debug information in the endpoint response
type PostIngestDebugEnum string

const (
	PostIngestDebugEnumTrue  PostIngestDebugEnum = "true"
	PostIngestDebugEnumFalse PostIngestDebugEnum = "false"
)

func (e PostIngestDebugEnum) ToPointer() *PostIngestDebugEnum {
	return &e
}

func (e *PostIngestDebugEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "true":
		fallthrough
	case "false":
		*e = PostIngestDebugEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostIngestDebugEnum: %s", s)
	}
}

type PostIngestRequest struct {
	RequestBody *PostIngestRequestBody `request:"mediaType=application/json"`
	// Flag to enable additional debug information in the endpoint response
	Debug *PostIngestDebugEnum `queryParam:"style=form,explode=true,name=debug"`
}

// PostIngest400ApplicationJSONDebug - Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
type PostIngest400ApplicationJSONDebug struct {
	Duplicate []string `json:"duplicate,omitempty"`
	Ingested  []string `json:"ingested,omitempty"`
}

type PostIngest400ApplicationJSONValidationFailed struct {
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// An array of objects corresponding to validation failures for each idempotency_key.
	ValidationErrors []string `json:"validation_errors,omitempty"`
}

// PostIngest400ApplicationJSON - Bad Request
type PostIngest400ApplicationJSON struct {
	// Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
	Debug *PostIngest400ApplicationJSONDebug `json:"debug,omitempty"`
	// Contains all failing validation events. In the case of a 400, there will be at least one entry in this array.
	ValidationFailed []PostIngest400ApplicationJSONValidationFailed `json:"validation_failed"`
}

// PostIngest200ApplicationJSONDebug - Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
type PostIngest200ApplicationJSONDebug struct {
	Duplicate []string `json:"duplicate,omitempty"`
	Ingested  []string `json:"ingested,omitempty"`
}

type PostIngest200ApplicationJSONValidationFailed struct {
	// The passed idempotency_key corresponding to the validation_errors
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// An array of objects corresponding to validation failures for each idempotency_key.
	ValidationErrors []map[string]interface{} `json:"validation_errors,omitempty"`
}

// PostIngest200ApplicationJSON - OK
type PostIngest200ApplicationJSON struct {
	// Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
	Debug *PostIngest200ApplicationJSONDebug `json:"debug,omitempty"`
	// Contains all failing validation events. In the case of a 200, this array will always be empty. This field will always be present.
	ValidationFailed []PostIngest200ApplicationJSONValidationFailed `json:"validation_failed"`
}

type PostIngestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostIngest200ApplicationJSONObject *PostIngest200ApplicationJSON
	// Bad Request
	PostIngest400ApplicationJSONObject *PostIngest400ApplicationJSON
}
