// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"Orb/pkg/types"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
)

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum - Determines the timing of the plan change
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnumRequestedDate         PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum = "requested_date"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnumEndOfSubscriptionTerm PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum = "end_of_subscription_term"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnumImmediate             PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum = "immediate"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "requested_date":
		fallthrough
	case "end_of_subscription_term":
		fallthrough
	case "immediate":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum: %s", s)
	}
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnumTieredBps PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum = "tiered_bps"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "tiered_bps":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum: %s", s)
	}
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers struct {
	Bps            float64 `json:"bps"`
	MaximumAmount  string  `json:"maximum_amount"`
	MinimumAmount  string  `json:"minimum_amount"`
	PerUnitMaximum string  `json:"per_unit_maximum"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfig struct {
	Tiers []PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers `json:"tiers"`
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 - Tiered BPS price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 struct {
	ID string `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount   *string                                                                                    `json:"minimum_amount,omitempty"`
	ModelType       PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum   `json:"model_type"`
	TieredBpsConfig PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfig `json:"tiered_bps_config"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfigTiers struct {
	Bps            float64 `json:"bps"`
	MaximumAmount  string  `json:"maximum_amount"`
	PerUnitMaximum string  `json:"per_unit_maximum"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfig struct {
	Tiers []PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfigTiers `json:"tiers,omitempty"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnumBulkBps PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum = "bulk_bps"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "bulk_bps":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum: %s", s)
	}
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 - Bulk BPS price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 struct {
	BulkBpsConfig *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfig `json:"bulk_bps_config,omitempty"`
	ID            string                                                                                    `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                                                  `json:"minimum_amount,omitempty"`
	ModelType     PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6ModelTypeEnum `json:"model_type"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5BpsConfig struct {
	Bps            float64 `json:"bps"`
	PerUnitMaximum string  `json:"per_unit_maximum"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnumBps PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum = "bps"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "bps":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum: %s", s)
	}
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 - BPS price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 struct {
	BpsConfig PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5BpsConfig `json:"bps_config"`
	ID        string                                                                               `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                                                  `json:"minimum_amount,omitempty"`
	ModelType     PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum `json:"model_type"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnumPackage PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum = "package"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "package":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum: %s", s)
	}
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4PackageConfig struct {
	NumUnits   float64 `json:"num_units"`
	UnitAmount string  `json:"unit_amount"`
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 - Package price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 struct {
	ID string `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                                                  `json:"minimum_amount,omitempty"`
	ModelType     PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4ModelTypeEnum `json:"model_type"`
	PackageConfig PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4PackageConfig `json:"package_config"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3BulkConfigTiers struct {
	MaximumUnits string `json:"maximum_units"`
	UnitAmount   string `json:"unit_amount"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3BulkConfig struct {
	Tiers []PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3BulkConfigTiers `json:"tiers"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnumBulk PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum = "bulk"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "bulk":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum: %s", s)
	}
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 - Bulk price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 struct {
	BulkConfig PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3BulkConfig `json:"bulk_config"`
	ID         string                                                                                `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                                                  `json:"minimum_amount,omitempty"`
	ModelType     PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum `json:"model_type"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnumUnit PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum = "unit"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "unit":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum: %s", s)
	}
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2UnitConfig struct {
	UnitAmount string `json:"unit_amount"`
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 - Unit price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 struct {
	ID string `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                                                  `json:"minimum_amount,omitempty"`
	ModelType     PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2ModelTypeEnum `json:"model_type"`
	UnitConfig    PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2UnitConfig    `json:"unit_config"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnumTiered PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum = "tiered"
)

func (e PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum) ToPointer() *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum {
	return &e
}

func (e *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "tiered":
		*e = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum: %s", s)
	}
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1TieredConfigTiers struct {
	FirstUnit  *string `json:"first_unit,omitempty"`
	LastUnit   *string `json:"last_unit,omitempty"`
	UnitAmount *string `json:"unit_amount,omitempty"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1TieredConfig struct {
	Tiers []PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1TieredConfigTiers `json:"tiers,omitempty"`
}

// PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 - Tiered price override
type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 struct {
	// price_id
	ID string `json:"id"`
	// The subscription's override minimum amount for this price.
	MinimumAmount *string                                                                                  `json:"minimum_amount,omitempty"`
	ModelType     PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1ModelTypeEnum `json:"model_type"`
	TieredConfig  PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1TieredConfig  `json:"tiered_config"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType string

const (
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_1"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_2"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_3"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_4"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_5"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_6"
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType = "post-subscriptions-subscription_id-schedule_plan_change_requestBody_price_overrides_7"
)

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides struct {
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6
	PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7

	Type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesType
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1,
		Type: typ,
	}
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2,
		Type: typ,
	}
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3,
		Type: typ,
	}
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4,
		Type: typ,
	}
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5,
		Type: typ,
	}
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6,
		Type: typ,
	}
}

func CreatePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesPostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7(postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7) PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides {
	typ := PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7

	return PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides{
		PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7: &postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7,
		Type: typ,
	}
}

func (u *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1
		return nil
	}

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2
		return nil
	}

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3
		return nil
	}

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4
		return nil
	}

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5
		return nil
	}

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6
		return nil
	}

	postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 := new(PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7); err == nil {
		u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 = postSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7
		u.Type = PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverridesTypePostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides) MarshalJSON() ([]byte, error) {
	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides1)
	}

	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides2)
	}

	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides3)
	}

	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides4)
	}

	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides5)
	}

	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides6)
	}

	if u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7 != nil {
		return json.Marshal(u.PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides7)
	}

	return nil, nil
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBody struct {
	// Reset billing periods to be aligned with the plan change’s effective date.
	AlignBillingWithPlanChangeDate *bool `json:"align_billing_with_plan_change_date,omitempty"`
	// The date that the plan change should take effect, localized to the customer's timezone. This parameter can only be passed if the `change_option` is `requested_date`.
	ChangeDate *types.Date `json:"change_date,omitempty"`
	// Determines the timing of the plan change
	ChangeOption PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyChangeOptionEnum `json:"change_option"`
	// The external_plan_id of the plan that the given subscription should be switched to. Note that either this property or `plan_id` must be specified.
	ExternalPlanID *string `json:"external_plan_id,omitempty"`
	// The subscription's override minimum amount for the plan.
	MinimumAmount *string `json:"minimum_amount,omitempty"`
	// The plan that the given subscription should be switched to. Note that either this property or `external_plan_id` must be specified.
	PlanID *string `json:"plan_id,omitempty"`
	// Optionally provide a list of overrides for prices on the plan
	PriceOverrides []PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBodyPriceOverrides `json:"price_overrides,omitempty"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeRequest struct {
	RequestBody    *PostSubscriptionsSubscriptionIDSchedulePlanChangeRequestBody `request:"mediaType=application/json"`
	SubscriptionID string                                                        `pathParam:"style=simple,explode=false,name=subscription_id"`
}

type PostSubscriptionsSubscriptionIDSchedulePlanChangeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Subscription *shared.Subscription
}
