// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

type PostCustomersCustomerIDBalanceTransactionsRequestBodyType string

const (
	PostCustomersCustomerIDBalanceTransactionsRequestBodyTypeIncrement PostCustomersCustomerIDBalanceTransactionsRequestBodyType = "increment"
	PostCustomersCustomerIDBalanceTransactionsRequestBodyTypeDecrement PostCustomersCustomerIDBalanceTransactionsRequestBodyType = "decrement"
)

func (e PostCustomersCustomerIDBalanceTransactionsRequestBodyType) ToPointer() *PostCustomersCustomerIDBalanceTransactionsRequestBodyType {
	return &e
}

func (e *PostCustomersCustomerIDBalanceTransactionsRequestBodyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "increment":
		fallthrough
	case "decrement":
		*e = PostCustomersCustomerIDBalanceTransactionsRequestBodyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostCustomersCustomerIDBalanceTransactionsRequestBodyType: %v", v)
	}
}

type PostCustomersCustomerIDBalanceTransactionsRequestBody struct {
	Amount string `json:"amount"`
	// An optional description that can be specified around this entry.
	Description *string                                                   `json:"description,omitempty"`
	Type        PostCustomersCustomerIDBalanceTransactionsRequestBodyType `json:"type"`
}

type PostCustomersCustomerIDBalanceTransactionsRequest struct {
	RequestBody *PostCustomersCustomerIDBalanceTransactionsRequestBody `request:"mediaType=application/json"`
	CustomerID  string                                                 `pathParam:"style=simple,explode=false,name=customer_id"`
}

type PostCustomersCustomerIDBalanceTransactionsResponse struct {
	ContentType string
	// OK
	CustomerBalanceTransaction *shared.CustomerBalanceTransaction
	StatusCode                 int
	RawResponse                *http.Response
}
