// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutDeprecateEventsEventIDRequest struct {
	// Identical to the `idempotency_key` provided on event ingestion. Uniquely identifies an event in the system.
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

// PutDeprecateEventsEventID400ApplicationJSON - Bad Request
type PutDeprecateEventsEventID400ApplicationJSON struct {
	// HTTP Code
	Status *int64 `json:"status,omitempty"`
	// Error message
	Title *string `json:"title,omitempty"`
	Type  *string `json:"type,omitempty"`
	// An array of strings corresponding to the validation failures
	ValidationErrors []string `json:"validation_errors,omitempty"`
}

// PutDeprecateEventsEventID200ApplicationJSON - OK
type PutDeprecateEventsEventID200ApplicationJSON struct {
	// event_id of the deprecated event, if successfully updated
	Deprecated *string `json:"deprecated,omitempty"`
}

type PutDeprecateEventsEventIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PutDeprecateEventsEventID200ApplicationJSONObject *PutDeprecateEventsEventID200ApplicationJSON
	// Bad Request
	PutDeprecateEventsEventID400ApplicationJSONObject *PutDeprecateEventsEventID400ApplicationJSON
}
