// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"time"
)

type PutEventsEventIDRequestBody struct {
	// The Orb Customer identifier
	CustomerID *string `json:"customer_id,omitempty"`
	// A name to meaningfully identify the action or event type.
	EventName string `json:"event_name"`
	// An alias for the Orb customer, whose mapping is specified when creating the customer
	ExternalCustomerID *string `json:"external_customer_id,omitempty"`
	// A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
	Properties map[string]interface{} `json:"properties"`
	// An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent the time that usage was recorded, and is particularly important to attribute usage to a given billing period.
	Timestamp time.Time `json:"timestamp"`
}

type PutEventsEventIDRequest struct {
	RequestBody *PutEventsEventIDRequestBody `request:"mediaType=application/json"`
	// Identical to the `idempotency_key` provided on event ingestion. Uniquely identifies an event in the system.
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

// PutEventsEventID400ApplicationJSON - Bad Request
type PutEventsEventID400ApplicationJSON struct {
	// HTTP Code
	Status *int64 `json:"status,omitempty"`
	// Error message
	Title *string `json:"title,omitempty"`
	Type  *string `json:"type,omitempty"`
	// An array of strings corresponding to the validation failures
	ValidationErrors []string `json:"validation_errors,omitempty"`
}

// PutEventsEventID200ApplicationJSON - OK
type PutEventsEventID200ApplicationJSON struct {
	// event_id of the amended event, if successfully ingested
	Amended *string `json:"amended,omitempty"`
}

type PutEventsEventIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PutEventsEventID200ApplicationJSONObject *PutEventsEventID200ApplicationJSON
	// Bad Request
	PutEventsEventID400ApplicationJSONObject *PutEventsEventID400ApplicationJSON
}
