// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type RevertBackfillRequest struct {
	BackfillID string `pathParam:"style=simple,explode=false,name=backfill_id"`
}

type RevertBackfillResponse struct {
	// OK
	Backfill    *shared.Backfill
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
