// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"net/http"
)

type UnscheduleCancellationRequest struct {
	SubscriptionID string `pathParam:"style=simple,explode=false,name=subscription_id"`
}

type UnscheduleCancellationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Subscription *shared.Subscription
}
