// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Orb/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

// UpdateCustomerExternalIDRequestBodyPaymentProvider - This is used for creating charges or invoices in an external system via Orb. When not in test mode:
// - the connection must first be configured in the Orb webapp.
// - if the provider is an invoicing provider (`stripe_invoice`, `quickbooks`, `bill.com`), any product mappings must first be configured with the Orb team.
type UpdateCustomerExternalIDRequestBodyPaymentProvider string

const (
	UpdateCustomerExternalIDRequestBodyPaymentProviderQuickbooks    UpdateCustomerExternalIDRequestBodyPaymentProvider = "quickbooks"
	UpdateCustomerExternalIDRequestBodyPaymentProviderStripeCharge  UpdateCustomerExternalIDRequestBodyPaymentProvider = "stripe_charge"
	UpdateCustomerExternalIDRequestBodyPaymentProviderStripeInvoice UpdateCustomerExternalIDRequestBodyPaymentProvider = "stripe_invoice"
	UpdateCustomerExternalIDRequestBodyPaymentProviderBillCom       UpdateCustomerExternalIDRequestBodyPaymentProvider = "bill.com"
	UpdateCustomerExternalIDRequestBodyPaymentProviderNull          UpdateCustomerExternalIDRequestBodyPaymentProvider = "null"
)

func (e UpdateCustomerExternalIDRequestBodyPaymentProvider) ToPointer() *UpdateCustomerExternalIDRequestBodyPaymentProvider {
	return &e
}

func (e *UpdateCustomerExternalIDRequestBodyPaymentProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "quickbooks":
		fallthrough
	case "stripe_charge":
		fallthrough
	case "stripe_invoice":
		fallthrough
	case "bill.com":
		fallthrough
	case "null":
		*e = UpdateCustomerExternalIDRequestBodyPaymentProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateCustomerExternalIDRequestBodyPaymentProvider: %v", v)
	}
}

type UpdateCustomerExternalIDRequestBody struct {
	// The customer's billing address; all fields in the address are optional. This address appears on customer invoices.
	BillingAddress *shared.BillingAddress `json:"billing_address,omitempty"`
	Email          *string                `json:"email,omitempty"`
	Name           *string                `json:"name,omitempty"`
	// This is used for creating charges or invoices in an external system via Orb. When not in test mode:
	// - the connection must first be configured in the Orb webapp.
	// - if the provider is an invoicing provider (`stripe_invoice`, `quickbooks`, `bill.com`), any product mappings must first be configured with the Orb team.
	PaymentProvider *UpdateCustomerExternalIDRequestBodyPaymentProvider `json:"payment_provider,omitempty"`
	// The ID of this customer in an external payments solution, such as Stripe. This is used for creating charges or invoices in the external system via Orb.
	PaymentProviderID *string `json:"payment_provider_id,omitempty"`
	// The customer's shipping address; all fields in the address are optional. Note that downstream tax calculations are based on the shipping address.
	ShippingAddress *shared.ShippingAddress `json:"shipping_address,omitempty"`
}

type UpdateCustomerExternalIDRequest struct {
	RequestBody        *UpdateCustomerExternalIDRequestBody `request:"mediaType=application/json"`
	ExternalCustomerID string                               `pathParam:"style=simple,explode=false,name=external_customer_id"`
}

type UpdateCustomerExternalIDResponse struct {
	ContentType string
	// OK
	Customer    *shared.Customer
	StatusCode  int
	RawResponse *http.Response
}
