// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BillingAddress - The customer's billing address; all fields in the address are optional. This address appears on customer invoices.
type BillingAddress struct {
	City *string `json:"city,omitempty"`
	// Two-letter country code (ISO 3166-1 alpha-2).
	Country *string `json:"country,omitempty"`
	Line1   *string `json:"line1,omitempty"`
	Line2   *string `json:"line2,omitempty"`
	// ZIP or postal code
	PostalCode *string `json:"postal_code,omitempty"`
	State      *string `json:"state,omitempty"`
}
