// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Coupon - A coupon represents a reusable discount configuration, and have an attached redemption code that can be issued to your end users. Coupons are most often used in self-serve signup or upgrade flows in your checkout experience or billing portal.
//
// To redeem a coupon, pass the `redemption_code` property in the [create subscription](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription) or [schedule plan change](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription-schedule-plan-change) request.
type Coupon struct {
	// An archived coupon can no longer be redeemed. Active coupons will have a value of null for `archived_at`; this field will be non-null for archived coupons.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`
	Discount   Discount   `json:"discount"`
	// This allows for a coupon's discount to apply for a limited time (determined in months); a `null` value here means "unlimited time".
	DurationInMonths *int64  `json:"duration_in_months,omitempty"`
	ID               *string `json:"id,omitempty"`
	// The maximum number of redemptions allowed for this coupon before it is exhausted; `null` here means "unlimited".
	MaxRedemptions *int64 `json:"max_redemptions,omitempty"`
	// This string can be used to redeem this coupon for a given subscription.
	RedemptionCode string `json:"redemption_code"`
	// The number of times this coupon has been redeemed.
	TimesRedeemed *int64 `json:"times_redeemed,omitempty"`
}

// CouponInput - A coupon represents a reusable discount configuration, and have an attached redemption code that can be issued to your end users. Coupons are most often used in self-serve signup or upgrade flows in your checkout experience or billing portal.
//
// To redeem a coupon, pass the `redemption_code` property in the [create subscription](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription) or [schedule plan change](https://docs.withorb.com/docs/orb-docs/api-reference/operations/create-a-subscription-schedule-plan-change) request.
type CouponInput struct {
	Discount Discount `json:"discount"`
	// This allows for a coupon's discount to apply for a limited time (determined in months); a `null` value here means "unlimited time".
	DurationInMonths *int64  `json:"duration_in_months,omitempty"`
	ID               *string `json:"id,omitempty"`
	// The maximum number of redemptions allowed for this coupon before it is exhausted; `null` here means "unlimited".
	MaxRedemptions *int64 `json:"max_redemptions,omitempty"`
	// This string can be used to redeem this coupon for a given subscription.
	RedemptionCode string `json:"redemption_code"`
	// The number of times this coupon has been redeemed.
	TimesRedeemed *int64 `json:"times_redeemed,omitempty"`
}
