// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreditNoteLineItemSubLineItems struct {
	Amount   string  `json:"amount"`
	Name     string  `json:"name"`
	Quantity float64 `json:"quantity"`
}

type CreditNoteLineItemTaxAmounts struct {
	Amount             string `json:"amount"`
	TaxRateDescription string `json:"tax_rate_description"`
	TaxRatePercentage  string `json:"tax_rate_percentage"`
}

type CreditNoteLineItem struct {
	// The amount of the line item, including any line item minimums and discounts
	Amount    string   `json:"amount"`
	Discounts Discount `json:"discounts"`
	// The Orb id of this resource
	ID string `json:"id"`
	// The name of the corresponding invoice line item
	Name string `json:"name"`
	// An optional quantity credited.
	Quantity float64 `json:"quantity"`
	// Any sub line items that may be credited.
	SubLineItems []CreditNoteLineItemSubLineItems `json:"sub_line_items"`
	// The amount of the line item, excluding any line item minimums and discounts
	Subtotal string `json:"subtotal"`
	// Any tax amounts applied onto the line item.
	TaxAmounts []CreditNoteLineItemTaxAmounts `json:"tax_amounts"`
}
