// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// CustomerBalanceTransactionActionEnum - Describes the reason that this transaction took place.
type CustomerBalanceTransactionActionEnum string

const (
	CustomerBalanceTransactionActionEnumAppliedToInvoice CustomerBalanceTransactionActionEnum = "applied_to_invoice"
	CustomerBalanceTransactionActionEnumProratedRefund   CustomerBalanceTransactionActionEnum = "prorated_refund"
	CustomerBalanceTransactionActionEnumManualAdjustment CustomerBalanceTransactionActionEnum = "manual_adjustment"
)

func (e *CustomerBalanceTransactionActionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "applied_to_invoice":
		fallthrough
	case "prorated_refund":
		fallthrough
	case "manual_adjustment":
		*e = CustomerBalanceTransactionActionEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerBalanceTransactionActionEnum: %s", s)
	}
}

// CustomerBalanceTransactionInvoice - The Invoice associated with this transaction
type CustomerBalanceTransactionInvoice struct {
	// The Invoice id
	ID string `json:"id"`
}

// CustomerBalanceTransaction - A single change to the customer balance. All amounts are in the customer's currency.
type CustomerBalanceTransaction struct {
	// Describes the reason that this transaction took place.
	Action CustomerBalanceTransactionActionEnum `json:"action"`
	// The value of the amount changed in the transaction.
	Amount string `json:"amount"`
	// The creation time of this transaction.
	CreatedAt time.Time `json:"created_at"`
	// An optional description provided for manual customer balance adjustments.
	Description string `json:"description"`
	// The new value of the customer's balance prior to the transaction, in the customer's currency.
	EndingBalance string `json:"ending_balance"`
	// A unique id for this transaction.
	ID string `json:"id"`
	// The Invoice associated with this transaction
	Invoice CustomerBalanceTransactionInvoice `json:"invoice"`
	// The original value of the customer's balance prior to the transaction, in the customer's currency.
	StartingBalance string `json:"starting_balance"`
}
