// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// CustomerPaymentProvider - The external payments or invoicing solution connected to this customer.
type CustomerPaymentProvider string

const (
	CustomerPaymentProviderStripe                 CustomerPaymentProvider = "stripe"
	CustomerPaymentProviderQuickbooks             CustomerPaymentProvider = "quickbooks"
	CustomerPaymentProviderBillCom                CustomerPaymentProvider = "bill.com"
	CustomerPaymentProviderStripeCharge           CustomerPaymentProvider = "stripe_charge"
	CustomerPaymentProviderStripeInvoice          CustomerPaymentProvider = "stripe_invoice"
	CustomerPaymentProviderLessThanNilGreaterThan CustomerPaymentProvider = "<nil>"
)

func (e CustomerPaymentProvider) ToPointer() *CustomerPaymentProvider {
	return &e
}

func (e *CustomerPaymentProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stripe":
		fallthrough
	case "quickbooks":
		fallthrough
	case "bill.com":
		fallthrough
	case "stripe_charge":
		fallthrough
	case "stripe_invoice":
		fallthrough
	case "<nil>":
		*e = CustomerPaymentProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerPaymentProvider: %v", v)
	}
}

// Customer - A customer is a buyer of your products, and the other party to the billing relationship.
//
// In Orb, customers are assigned system generated identifiers automatically, but it's often desirable to have these match existing identifiers in your system. To avoid having to denormalize Orb ID information, you can pass in an `external_customer_id` with your own identifier. See [Customer ID Aliases](../guides/events-and-metrics/customer-aliases) for further information about how these aliases work in Orb.
//
// In addition to having an identifier in your system, a customer may exist in a payment provider solution like Stripe. Use the `payment_provider_id` and the `payment_provider` enum field to express this mapping.
//
// A customer also has a timezone (from the standard [IANA timezone database](https://www.iana.org/time-zones)), which defaults to your account's timezone. See [Timezone localization](../guides/product-catalog/) for information on what this timezone parameter influences within Orb.
type Customer struct {
	// Determines whether Orb attempts to automatically collect payment for issued invoices from the saved payment method.  Note that if payment provider is set, auto collection will be turned on unless explicitly updated.
	AutoCollection *bool `json:"auto_collection,omitempty"`
	// The customer's current balance in their currency.
	Balance string `json:"balance"`
	// The customer's billing address; all fields in the address are optional. This address appears on customer invoices.
	BillingAddress *BillingAddress `json:"billing_address,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	// An ISO 4217 currency string used for the customer's invoices and balance.
	Currency string `json:"currency"`
	// A valid customer email, to be used for notifications. When Orb triggers payment through a payment gateway, this email will be used for any automatically issued receipts.
	Email string `json:"email"`
	// Determines whether Orb will send automated emails to this customer. This setting is superseded by the account-wide email setting for email delivery.
	EmailDelivery *bool `json:"email_delivery,omitempty"`
	// An optional user-defined ID for this customer resource, used throughout the system as an alias for this Customer. Use this field to identify a customer by an existing identifier in your system.
	ExternalCustomerID *string `json:"external_customer_id,omitempty"`
	// The full name of the customer
	ID string `json:"id"`
	// User specified key-value pairs. If there is no metadata for the customer, this defaults to an empty dictionary.
	Metadata map[string]interface{} `json:"metadata"`
	Name     string                 `json:"name"`
	// The external payments or invoicing solution connected to this customer.
	PaymentProvider CustomerPaymentProvider `json:"payment_provider"`
	// The ID of this customer in an external payments solution, such as Stripe. This is used for creating charges or invoices in the external system via Orb.
	PaymentProviderID string `json:"payment_provider_id"`
	// The customer's shipping address; all fields in the address are optional. Note that downstream tax calculations are based on the shipping address.
	ShippingAddress *ShippingAddress `json:"shipping_address,omitempty"`
	// Tax IDs are commonly required to be displayed on customer invoices, which are added to the headers of invoices.
	//
	//
	// ### Supported Tax ID Countries and Types
	//
	//
	// | Country        | Type         | Description                                 |
	// |----------------|--------------|---------------------------------------------|
	// | Australia      | `au_abn`     | Australian Business Number (AU ABN)	        |
	// | Australia      | `au_arn`     | Australian Taxation Office Reference Number |
	// | Austria        | `eu_vat`     | European VAT number                         |
	// | Belgium        | `eu_vat`     | European VAT number                         |
	// | Brazil         | `br_cnpj`    | Brazilian CNPJ number                       |
	// | Brazil         | `br_cpf`     | Brazilian CPF number	                       |
	// | Bulgaria       | `bg_uic`     | Bulgaria Unified Identification Code        |
	// | Bulgaria       | `eu_vat`     | European VAT number                         |
	// | Canada         | `ca_bn`      | Canadian BN                                 |
	// | Canada         | `ca_gst_hst` | Canadian GST/HST number                     |
	// | Canada         | `ca_pst_bc`  | Canadian PST number (British Columbia)      |
	// | Canada         | `ca_pst_mb`  | Canadian PST number (Manitoba)              |
	// | Canada         | `ca_pst_sk`  | Canadian PST number (Saskatchewan)          |
	// | Canada         | `ca_qst`     | Canadian QST number (Québec)                |
	// | Chile          | `cl_tin`     | Chilean TIN                                 |
	// | Croatia        | `eu_vat`     | European VAT number                         |
	// | Cyprus         | `eu_vat`     | European VAT number                         |
	// | Czech Republic | `eu_vat`     | European VAT number                         |
	// | Denmark        | `eu_vat`     | European VAT number                         |
	// | Egypt          | `eg_tin`     | Egyptian Tax Identification Number	         |
	// | Estonia   | `eu_vat`     | European VAT number   |
	// | EU        | `eu_oss_vat` | European One Stop Shop VAT number for non-Union scheme                                                   |
	// | Finland   | `eu_vat`     | European VAT number                                                                                      |
	// | France    | `eu_vat`     | European VAT number                                                                                      |
	// | Georgia   | `ge_vat`     | Georgian VAT                                                                                             |
	// | Germany   | `eu_vat`     | European VAT number                                                                                      |
	// | Greece    | `eu_vat`     | European VAT number                                                                                      |
	// | Hong Kong | `hk_br`      | Hong Kong BR number                                                                                      |
	// | Hungary   | `eu_vat`     | European VAT number                                                                                      |
	// | Hungary   | `hu_tin`     | Hungary tax number (adószám)	                                                                            |
	// | Iceland   | `is_vat`     | Icelandic VAT                                                                                            |
	// | India     | `in_gst`     | Indian GST number                                                                                        |
	// | Indonesia | `id_npwp`    | Indonesian NPWP number                                                                                   |
	// | Ireland   | `eu_vat`     | European VAT number                                                                                      |
	// | Israel    | `il_vat`     | Israel VAT                                                                                               |
	// | Italy     | `eu_vat`     | European VAT number                                                                                      |
	// | Japan     | `jp_cn`      | Japanese Corporate Number (*Hōjin Bangō*)                                                                |
	// | Japan     | `jp_rn`      | Japanese Registered Foreign Businesses' Registration Number (*Tōroku Kokugai Jigyōsha no Tōroku Bangō*)	 |
	// | Japan     | `jp_trn`     | Japanese Tax Registration Number (*Tōroku Bangō*)	                                                       |
	// | Kenya     | `ke_pin`     | Kenya Revenue Authority Personal Identification Number                                                   |
	// | Latvia    | `eu_vat`     | European VAT number                                                                                  |
	// | Liechtenstein | `li_uid`  | Liechtensteinian UID number           |
	// | Lithuania     | `eu_vat`  | European VAT number	                  |
	// | Luxembourg    | `eu_vat`  | European VAT number	                  |
	// | Malaysia      | `my_frp`  | Malaysian FRP number                  |
	// | Malaysia      | `my_itn`  | Malaysian ITN                         |
	// | Malaysia      | `my_sst`  | Malaysian SST number                  |
	// | Malta         | `eu_vat ` | European VAT number                   |
	// | Mexico        | `mx_rfc`  | Mexican RFC number                    |
	// | Netherlands   | `eu_vat`  | European VAT number	                  |
	// | New Zealand   | `nz_gst`  | New Zealand GST number	               |
	// | Norway        | `no_vat`  | Norwegian VAT number                  |
	// | Philippines   | `ph_tin	` | Philippines Tax Identification Number |
	// | Poland        | `eu_vat`  | European VAT number                   |
	// | Portugal      | `eu_vat`  | European VAT number                   |
	// | Romania       | `eu_vat`  | European VAT number                   |
	// | Russia        | `ru_inn`  | Russian INN                           |
	// | Russia        | `ru_kpp`  | Russian KPP                           |
	// | Saudi Arabia  | `sg_gst`  | Singaporean GST                       |
	// | Singapore     | `sg_uen`  | Singaporean UEN	                      |
	// | Slovakia      | `eu_vat`  | European VAT number                   |
	// | Slovenia      | `eu_vat`  | European VAT number                   |
	// | Slovenia             | `si_tin` | Slovenia tax number (davčna številka)	             |
	// | South Africa	        | `za_vat` | South African VAT number                           |
	// | South Korea          | `kr_brn` | Korean BRN                                         |
	// | Spain                | `es_cif` | Spanish NIF number (previously Spanish CIF number) |
	// | Spain                | `eu_vat` | European VAT number	                               |
	// | Sweden               | `eu_vat` | European VAT number                                |
	// | Switzerland          | `ch_vat` | Switzerland VAT number	                            |
	// | Taiwan               | `tw_vat` | Taiwanese VAT	                                     |
	// | Thailand             | `th_vat` | Thai VAT                                           |
	// | Turkey               | `tr_tin` | Turkish Tax Identification Number                  |
	// | Ukraine              | `ua_vat` | Ukrainian VAT                                      |
	// | United Arab Emirates | `ae_trn` | United Arab Emirates TRN	                          |
	// | United Kingdom       | `eu_vat` | Northern Ireland VAT number                        |
	// | United Kingdom       | `gb_vat` | United Kingdom VAT number                          |
	// | United States        | `us_ein` | United States EIN                                  |
	//
	//
	TaxID CustomerTaxID `json:"tax_id"`
	// A timezone identifier from the IANA timezone database, such as "America/Los_Angeles". This defaults to your account's timezone if not set. This cannot be changed after customer creation.
	Timezone string `json:"timezone"`
}
