// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// PlanBasePlan - The parent plan if the given plan was created by overriding one or more of the parent's prices
type PlanBasePlan struct {
	ExternalPlanID *string `json:"external_plan_id,omitempty"`
	ID             *string `json:"id,omitempty"`
	Name           *string `json:"name,omitempty"`
}

type PlanProduct struct {
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
	Name      string    `json:"name"`
}

type PlanTrialConfigTrialPeriodUnit string

const (
	PlanTrialConfigTrialPeriodUnitDays PlanTrialConfigTrialPeriodUnit = "days"
)

func (e PlanTrialConfigTrialPeriodUnit) ToPointer() *PlanTrialConfigTrialPeriodUnit {
	return &e
}

func (e *PlanTrialConfigTrialPeriodUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "days":
		*e = PlanTrialConfigTrialPeriodUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlanTrialConfigTrialPeriodUnit: %v", v)
	}
}

type PlanTrialConfig struct {
	TrialPeriod     *float64                       `json:"trial_period,omitempty"`
	TrialPeriodUnit PlanTrialConfigTrialPeriodUnit `json:"trial_period_unit"`
}

// Plan - OK
type Plan struct {
	// The parent plan if the given plan was created by overriding one or more of the parent's prices
	BasePlan *PlanBasePlan `json:"base_plan,omitempty"`
	// The parent plan id if the given plan was created by overriding one or more of the parent's prices
	BasePlanID *string   `json:"base_plan_id,omitempty"`
	CreatedAt  time.Time `json:"created_at"`
	// An ISO 4217 currency string or custom pricing unit (`credits`) for this plan's prices.
	Currency string `json:"currency"`
	// The default memo text on the invoices corresponding to subscriptions on this plan. Note that each subscription may configure its own memo.
	DefaultInvoiceMemo *string  `json:"default_invoice_memo,omitempty"`
	Description        string   `json:"description"`
	Discount           Discount `json:"discount"`
	// An optional user-defined ID for this plan resource, used throughout the system as an alias for this Plan. Use this field to identify a plan by an existing identifier in your system.
	ExternalPlanID *string `json:"external_plan_id,omitempty"`
	ID             string  `json:"id"`
	// An ISO 4217 currency string for which this plan is billed in. Matches `currency` unless `currency` is a custom pricing unit.
	InvoicingCurrency string        `json:"invoicing_currency"`
	Minimum           MinimumAmount `json:"minimum"`
	Name              string        `json:"name"`
	// Determines the difference between the invoice issue date and the due date. A value of "0" here signifies that invoices are due on issue, whereas a value of "30" means that the customer has a month to pay the invoice before its overdue. Note that individual subscriptions or invoices may set a different net terms configuration.
	NetTerms   *int64      `json:"net_terms,omitempty"`
	PlanPhases []PlanPhase `json:"plan_phases,omitempty"`
	// Prices for this plan. If the plan has phases, this includes prices across all phases of the plan.
	Prices      []Price          `json:"prices"`
	Product     PlanProduct      `json:"product"`
	TrialConfig *PlanTrialConfig `json:"trial_config,omitempty"`
}
